import './globals.css'

// HTML meta
export const metadata = {
  title: 'Next tutorial',
  description: 'Generated by lee',
}

// page.js 에서 리턴하는 부분을 children이 받음
export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <ul>
          <li>
            <a href="/">Home</a>
          </li>
          <li>
            <a href="/create">Create</a>
          </li>
        </ul>
        {children}
      </body>
    </html>
  )
}
